/**
 * Core redemption types and the {@link RedemptionStore} contract.
 *
 * Encoding/decoding logic lives in BytKey core, outside the store abstraction.
 * The store only owns atomic persistence and lookup of redemption records.
 */

import type { BoolField, DataField, EnumField, IntField, Schema, SchemaDef } from "./schema.ts";

/**
 * The decoded value type for a single schema field.
 */
export type FieldValue<F extends DataField> = F extends IntField
  ? number
  : F extends BoolField
    ? boolean
    : F extends EnumField
      ? F["values"][number]
      : never;

/**
 * Decoded data values for a redemption, keyed by field name.
 *
 * Each value is typed to match the corresponding field's kind in the schema.
 */
export type RedemptionData<T extends SchemaDef> = {
  readonly [K in T["fields"][number] as K["name"]]: FieldValue<K>;
};

/**
 * A redemption record as stored by a {@link RedemptionStore}.
 *
 * Every redemption is tied to the schema that produced its decoded data. The
 * store generates the timestamp at the moment the redemption succeeds.
 * Connectors may store richer metadata via the optional `extra` payload.
 */
export interface Redemption<T extends Schema, Extra = unknown> {
  /** The unique code id that was redeemed. */
  readonly id: string;

  /** The stable ID of the schema this redemption belongs to. */
  readonly schemaID: string;

  /** When the redemption succeeded, generated by the store. */
  readonly redeemedAt: Date;

  /** Decoded data values by field name, typed to the schema. */
  readonly data: RedemptionData<T>;

  /** Optional implementation-specific metadata attached at redemption time. */
  readonly extra?: Extra;
}

/**
 * Minimal contract for atomically redeeming codes and retrieving records.
 *
 * Every redemption is associated with the schema that defines its data shape.
 * Implementations must guarantee that two concurrent calls to
 * {@link RedemptionStore.redeem} for the same `id` cannot both succeed.
 * The second call must reject with an already-redeemed error.
 */
export interface RedemptionStore<Extra = unknown> {
  /**
   * Atomically redeem a code.
   *
   * Stores a {@link Redemption} record with a store-generated timestamp and
   * returns it. If `id` has already been redeemed, the call rejects.
   */
  redeem<T extends Schema>(
    id: string,
    schema: T,
    data: RedemptionData<T>,
    extra?: Extra,
  ): Promise<Redemption<T, Extra>>;

  /** Return `true` if the code has already been redeemed. */
  isRedeemed(id: string): Promise<boolean>;

  /** Look up a redemption by code id. Returns `null` if not found. */
  getRedemption<T extends Schema>(id: string, schema: T): Promise<Redemption<T, Extra> | null>;
}

/**
 * Optional extension for backends that can enumerate redemption records.
 *
 * Admin/debug tooling can use this without forcing minimal implementations to
 * support listing.
 */
export interface QueryableRedemptionStore<Extra = unknown> extends RedemptionStore<Extra> {
  /** Return all stored redemptions in an implementation-defined order. */
  listRedemptions(): Promise<ReadonlyArray<Redemption<Schema, Extra>>>;
}
